
% reconstruct 
%{
a = [         ...
    1 1;      ...
    2 2;      ...
    3 6;      ...
    5 7;      ...
    ];
[pca_coef pca_score]=princomp(a);
ndim=1;
reconstructed = repmat(mean(a,1),size(a,1),1) + pca_score(:,1:ndim)*pca_coef(:,1:ndim)'; 
reconstructed
%}
